development:
  adapter: postgresql
  database: htn_dev
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1

test:
  adapter: postgresql
  database: htn_test
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1

production:
  adapter: postgresql
  database: htn_production
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1
